### ISSUE TITLE
Benchmarking: track output tokens required

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#114]
Different edit formats can improve the success rate of Mentat, but not all edit formats are as concise. For example we could ask GPT-4 to rewrite entire files, which would be easier than specifying edits that involve insertions / deletions. But this would be slow (and more expensive!) to use.

To keep track of this we should record how many tokens the models generate while using each edit format during benchmarks. Comparison is tricky as different tasks will require different numbers of tokens. Perhaps we could choose a set of exercises that are all solved on the first attempt when using each edit format.

**Comment by jakethekoenig** [comment]
This is a really good idea particularly as in initial results it seems like different edit formats have only a small affect on accuracy. Comparing on the subset of exercises that are completed in the same number of steps seems like a good idea. Another thing to think about is system prompt versus assistant edit tokens. Hopefully the system prompts will be dropped after fine tuning so we should maybe not count the system tokens towards the total. Or at least count them separately.

If I was to work on this today I'd probably mock out the [cost tracker](https://github.com/AbanteAI/mentat/blob/b578510646823f9c264ee49e0069155f7d2a24f6/mentat/llm_api.py#L156) to report the cost back to the thread sort of like how the user input manager is mocked out [here](https://github.com/AbanteAI/mentat/blob/b578510646823f9c264ee49e0069155f7d2a24f6/tests/benchmarks/exercism_practice.py#L63). But I was hoping after the interface refactor it would be possible to create a session and send messages to it and access the cost directly and not need to mock anything i.e. the test could interact with mentat exactly as the terminal or a vscode extension would.

**Comment by biobootloader** [comment]
> Another thing to think about is system prompt versus assistant edit tokens.

Ah, true! Yeah system tokens wouldn't impact speed of responses but do impact cost, so they should also be compared when considering formats.

> But I was hoping after the interface refactor it would be possible to create a session and send messages to it and access the cost directly and not need to mock anything i.e. the test could interact with mentat exactly as the terminal or a vscode extension would.

Yeah lets wait for that!
