### ISSUE TITLE
Add Command Line Option for Model Selection

### ISSUE THREAD

**Issue by AntreasAntoniou** [AbanteAI/mentat#139]
#### Problem Statement:
The current implementation of Mentat does not allow users to choose which language model to use, including the more advanced GPT-4 and its 32K version. 

#### Proposed Solution:
- Implement a command-line option, for example, `--model`, that lets users specify the language model they want to use.
- Include validation to ensure the specified model is supported.
  
#### Acceptance Criteria:
- A user can specify the model via the command line.
- The system validates the model name against the supported models and returns an error if it's not supported.

#### Priority: High
🛠️ This feature is key to user customization and leveraging the full potential of the latest language models.

**Comment by biobootloader** [comment]
You can choose the model, as documented here: https://github.com/AbanteAI/mentat/blob/main/docs/configuration.md

But it would be good to have a command line option as well!
