### ISSUE TITLE
`tests/record_benchmark.py` should use standard config settings

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#155]
When you run benchmarks with this script now, it's going to use whatever settings you have in your mentat config. These could be changed models, maximum context, and potentially in the future code maps or context settings. All of these would significantly impact performance. We should instead run with standard settings defined in the benchmark file, or support a way to run with different settings and record those settings with the results.

**Comment by biobootloader** [comment]
Related: https://github.com/AbanteAI/mentat/issues/154

**Comment by PCSwingle** [comment]
Right now all tests mock the user config; they only care about the git project config (which is always unset in the testbed) and the default config file (which isn't the 'users' config). I think it could be a good idea to add an easy way to change the config, but it isn't too difficult right now (all you need to do is open a file in the git repo setting the config).

**Comment by biobootloader** [comment]
Ah, nice!
