### ISSUE TITLE
Connecting Mentat to Azure OpenAI

### ISSUE THREAD

**Issue by gssakash-SxT** [AbanteAI/mentat#158]
I'm having problems having Mentat connect to my GPT 4 model provided by Azure.
I already have Azure OpenAI Access with a model and a URL specific to Azure to be used with OpenAI with me.

I set these variables by doing
``openai.api_key = os.environ["OPENAI_API_KEY"]
``
``
    openai.api_base = os.environ["OPENAI_API_BASE"]
``

And then use this provided model in the ``ChatCompletion.create`` function by having an extra engine parameter where I give it name of my Model. I am trying to use the 32k Context provided by Mentat and have all of the configuration ready for it. 

However, I'm not sure if Mentat is getting successfully connected to this 32k Context model and to Azure.
I would like to know the steps to be taken in general to be able to do so

P.S. I already have 32k tokens available as a part of my Azure Subscription and this error mainly occurs when dealing with the ``Call_LLM_API function`` inside ``llm_api.py``

**Comment by biobootloader** [comment]
Have you tried following the instructions here: [alternative-models](https://github.com/AbanteAI/mentat/blob/main/docs/configuration.md#-alternative-models) ? 

What is the error you are getting, can you paste that here?

Also, when Mentat starts you'll see something like this printed: `Prompt and included files token count: 1512 / 8192` - that shows the token limit it thinks the model you're using has, so should confirm if you've set things up.

**Comment by gssakash-SxT** [comment]
@biobootloader  I'm making a few configurations inside ``llm_api.py`` file.
For example, I'm setting the ``openai.api_version``, ``openai.api_type`` along with the ``openai.api_base`` and ``openai.api_key`` inside it.

And, AFAIK I'm getting an error from here. I am using Azure OpenAI and the standard convention for it is to mention an Engine instead of Model in the below function - This is well tested as I've been using this for a while.

```    response: AsyncGenerator[Any, None] = cast(
        AsyncGenerator[Any, None],
        await openai.ChatCompletion.acreate(  # type: ignore
            engine=my_model, # Where my_model is the name of the model given by Azure to me.
            messages=messages,
            temperature=0.5,
            stream=True,
        ),
    ) 
```

This error comes from this particular source of the code base - https://github.com/AbanteAI/mentat/blob/63595ace4ae8fb45f96ac56e83e22958cf0fd70e/mentat/conversation.py#L130

And Here's the Error Message : - 
`mentat.errors.MentatError: Something went wrong - invalid request to OpenAI API. OpenAI returned:
Resource not found`

P.S. I have tried switching the name of the model from the one given by Azure to the generic ``gpt-4-0314`` as well and it still doesn't get fixed. Please let me know if you need more details

**Comment by gssakash-SxT** [comment]
Okay I've managed to fix the above error ^.
But then I notice that Mentat tends to default to the 8k context model instead of 32k context model despite me adding in the ``.mentat_config.json`` file. Am I doing something wrong here?

``
{
    "model":"gpt-4-32k-0314",
    "maximum-context": 32000
}
``

Tagging relevant people - @biobootloader @jakethekoenig . I appreciate your guys help!

**Comment by jakethekoenig** [comment]
Are you sure you're editing the right file? What is the output of:
`cat ~/.mentat/.mentat_config.json` and `cat mentat_config.json`?
When you run `mentat` what is the denominator for "Prompt and included files token count"?

**Comment by gssakash-SxT** [comment]
Okay so, I've set the above mentat configuration json on ``~/.mentat/.mentat_config.json`` and it seems to be working and is now picking the right model. 
However I want to know why it isn't exactly pointing to my project's local ``mentat_config.json`` and this does exist as after I do ``cat .mentat_config.json``,   I get the expected output - 

``
{
    "model":"gpt-4-32k-0314",
    "maximum-context": 32000
}
``

**Comment by jakethekoenig** [comment]
Are you running `mentat` from the root of a git project?

**Comment by gssakash-SxT** [comment]
UPDATE : This seems to be fixed and can be successfully closed @jakethekoenig . Appreciate the help!
Turns out My JSON file seemed to be corrupted or something along that line causing this issue

**Comment by jakethekoenig** [comment]
Glad you got it working! Sorry you had some difficulties.

**Comment by zhh210** [comment]
Any example that works with Azure's gpt-35-turbo? My ~/.mentat/.mentat_config.json is
```
{ "model":"gpt-35-turbo", "maximum-context": 16000 }
```
My .env has the keys/configs that worked with other llm apps but fails with mentat:
```
OPENAI_DEPLOYMENT_ENDPOINT = xxx
OPENAI_API_KEY = xxx
OPENAI_DEPLOYMENT_NAME = "gpt-35-turbo"
OPENAI_GPT_DEPLOYMENT_NAME = "gpt-35-turbo"                                                      
OPENAI_DEPLOYMENT_VERSION = "2023-03-15-preview"
OPENAI_MODEL_NAME="gpt-35-turbo"
OPENAI_API_BASE = xxx

OPENAI_EMBEDDING_DEPLOYMENT_NAME = "text-embedding-ada-002"
OPENAI_EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
```
It's unclear to me what the error is saying:
```
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/envs/py311/bin/mentat", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/mentat/terminal/client.py", line 261, in run_cli
    terminal_client.run()
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/mentat/terminal/client.py", line 192, in run
    asyncio.run(self._run())
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/mentat/terminal/client.py", line 187, in _run
    await self._startup()
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/mentat/terminal/client.py", line 119, in _startup
    self.session = await Session.create(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/mentat/session.py", line 91, in create
    return cls(stream)
           ^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/mentat/session.py", line 42, in __init__
    setup_api_key()
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/mentat/llm_api.py", line 42, in setup_api_key
    openai.Model.list()  # type: ignore Test the API key
    ^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/openai/api_resources/abstract/listable_api_resource.py", line 60, in list
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/home/ec2-user/SageMaker/envs/py311/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
```
