### ISSUE TITLE
Collect anonymous usage statistics

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#165]
It'd be really useful to know how users are using Mentat, what crashes / errors they are encountering, etc. At the same time we need to respect user privacy and be clear about what is collected.

We could let users opt out of sending details on:
- usage stats (models used, tokens, costs, commands, how often edits are accepted/rejected)
- crashes / errors encountered

For more detailed info, we could let users opt in to providing:
- full transcripts of Mentat sessions

**Comment by waydegg** [comment]
Thinking we can use [Sentry](https://docs.sentry.io/platforms/python/?original_referrer=https%3A%2F%2Fsentry.io%2F) for this

**Comment by waydegg** [comment]
[Posthog](https://github.com/posthog/posthog) is another option, see how [Chroma](https://github.com/chroma-core/chroma) uses it for a production reference
