### ISSUE TITLE
Add /add and /remove commands to add/remove files from context

### ISSUE THREAD

**Issue by ztxtz** [AbanteAI/mentat#17]
Add a command to add / remove files from the context inside of the current session to avoid having to restart it after each edit.

**Comment by biobootloader** [comment]
@PCSwingle will be working on this this weekend!

**Comment by ztxtz** [comment]
@biobootloader I'm not able to view the discord channel without joining the server first. Do you have an invite?

**Comment by biobootloader** [comment]
Here you go! https://discord.com/invite/zbvd9qx9Pb

**Comment by biobootloader** [comment]
Now that we've added commands (`/help` and `/commit` so far), we can add `/add` and `/remove` to modify which files are included in the conversation

**Comment by waydegg** [comment]
I'll work on a PR for this

**Comment by jakethekoenig** [comment]
Closed by the linked pr but the commands have since become `/include` `/exclude`.
