### ISSUE TITLE
Warning of "Attempted to edit file not in context" should be caught before accepting changes

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#173]
If the model tries to edit a file that's not in context, we don't do anything about it until after the user accepts changes. And then we say "Changes applied." even if nothing has been applied (if all the edits were for out-of-context files).

Really the root issue is the model trying to edit files that aren't in context, but still we could handle this better

<img width="1192" alt="image" src="https://github.com/AbanteAI/mentat/assets/128252497/1b8e982b-f29e-42b1-b4ee-7ee359cfa378">

**Comment by PCSwingle** [comment]
I'm actually not sure how this happened for you; for me, it checks before I say y/n and says it isn't in context and cancels the edit (in is_valid of file_edit)

**Comment by biobootloader** [comment]
I just reproduced - with the latest code run with `--auto-tokens 6000` and ask it to edit the multifile calculator like this:

<img width="1059" alt="image" src="https://github.com/AbanteAI/mentat/assets/128252497/d6d0382f-fd44-4406-b8a0-50fdaca361c9">

**Comment by biobootloader** [comment]
Aha! we have two separate checks. I tried running again now without any autotokens, and now it won't let me approve edits to files not in context. So it depends on if the file was added automatically or not

<img width="1196" alt="image" src="https://github.com/AbanteAI/mentat/assets/128252497/2347c0fe-a0de-476e-aa2c-0d5281bf3544">

**Comment by PCSwingle** [comment]
Ah, I just realized why. For whatever reason, we're checking code_file_manager.file_lines, not code_context.include_files (which is what the context is). The file_lines gets updated whenever we read a file (which we might want to change, I'm not sure we want that functionality?), so auto-tokens was reading the file, therefore adding it to file_lines. I'll fix this now
