### ISSUE TITLE
Printing output of Mentat's execution on the Mentat Python Client

### ISSUE THREAD

**Issue by gssakash-SxT** [AbanteAI/mentat#187]
I'd like to suggest a feature to print the output of the steps Mentat takes on the ``Mentat Python client`` similar to how it prints out a bunch of outputs when you run ``mentat .`` via an terminal.
I'm looking for something like this but for the ``Mentat Python Client`` - 

![image](https://github.com/AbanteAI/mentat/assets/126104954/8c0db1c6-0a8a-43bd-87d1-ed47c8de4e26)

**Comment by biobootloader** [comment]
Hey @gssakash-SxT, take a look at how I use the accumulated message feature of `PythonClient` here: https://github.com/AbanteAI/mentat/pull/205/files

Does that work for your use case? It'd be more flexible than printing all the output

**Comment by gssakash-SxT** [comment]
This can be closed now, I've managed to figure out a temporary fix similar to what has been suggested above ^^
