### ISSUE TITLE
Commands with arguments with unclosed quotes throw exceptions

### ISSUE THREAD

**Issue by jakethekoenig** [AbanteAI/mentat#192]
For example `/search where's the parser` throws an exception. I propose we put a try catch [here](https://github.com/AbanteAI/mentat/blob/2a61ead72e841f74f8a993565ef65238003fc959/mentat/session_input.py#L35) and if there's an exception we can split on the first space and take every after as a singly string typed argument. Alternatively we could give a warning and it can be up to the user to rerun with quotes.

**Comment by PCSwingle** [comment]
I agree that we shouldn't throw an exception, but I don't think we should change the behavior away from shlex.split (which uses the same parsing a command line does). I think we should just print 'Invalid arguments' or somehow convey the error to the user without allowing invalid syntax.
