### ISSUE TITLE
`black` not formatting on commit/merge

### ISSUE THREAD

**Issue by waydegg** [AbanteAI/mentat#218]
As of writing this, there's about 22 files that aren't formatted by `black` that are checked into the main branch. A solution to this could be to just format code as part of the github actions workflow, then run tests after.

**Comment by waydegg** [comment]
See https://github.com/AbanteAI/mentat/pull/217#issuecomment-1778576058

**Comment by biobootloader** [comment]
I thought we did have `black` checking in github actions here:

https://github.com/AbanteAI/mentat/blob/6f27ae6031a44429860af5defac9082aa4ce9c36/.github/workflows/lint_and_test.yml#L24-L25

is it not working?

**Comment by waydegg** [comment]
It's working, didn't need to open this issue (this was a problem on my end)
