### ISSUE TITLE
Reconsider behavior of what files are included with -diff and --pr-diff flags

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#243]
https://github.com/AbanteAI/mentat/pull/241#issuecomment-1792309162 :

> I'm not entirely sure the behavior is what users will expect. I personally would expect all the changed files to always be added to the context if --diff was included. This is a more complicated change but maybe it would be best to include intervals around the actual changes so much larger changes would have a hope of fitting in context?

> Yeah that seems like it'd be the more expected behavior. I'll make an issue to discuss and potentially change this, it'll be easier once we have function-level features instead of whole files, so even diffs touching a lot of files can be added.

**Comment by PCSwingle** [comment]
I think I looked at this about a month ago and determined that the behavior was all correct; I'm in favor of closing this issue.
