### ISSUE TITLE
Ability to allow the Python Client to work on the specific sub-directories

### ISSUE THREAD

**Issue by gssakash-SxT** [AbanteAI/mentat#256]
Hi, This seems to be like a little bit of a tough feature to add but it'd be quite helpful to users.

On the [Python Client](https://github.com/AbanteAI/mentat/blob/main/mentat/python_client/client.py) , I feel like it'd be beneficial to the users if you can add a way to allow the users to have Mentat work on specific sub-directories instead of ALL of the sub-directories which I believe is what it does right now.

I feel like allowing users to pick and choose a subdirectory of their liking where Mentat should start executing code would be a great addition to the Python Client instead of it working on the whole directory. 

For example let's say I have a directory structure like so - 

```
└── my_directory
    ├── tests
    └── sample_code_files
                ├── my_main_code
```

It'd be great for Mentat to be able to work on the code files ONLY inside - ``my_directory / sample_code_files / my_main_code`` given this path.

**Comment by jakethekoenig** [comment]
You already can! The python client accepts a [paths](https://github.com/AbanteAI/mentat/blob/3edd4597eca1dc8eb3998e21a37bfe18474c1adc/mentat/python_client/client.py#L15) argument. This argument is glob expanded [here](https://github.com/AbanteAI/mentat/blob/3edd4597eca1dc8eb3998e21a37bfe18474c1adc/mentat/include_files.py#L18). For an example in our code base you can see our [exercism benchmark](https://github.com/AbanteAI/mentat/blob/3edd4597eca1dc8eb3998e21a37bfe18474c1adc/tests/benchmarks/exercism_practice.py#L108). So in your example you can run:
```
from pathlib import Path # If not already imported
client = PythonClient(
        paths=[Path("my_directory/sample_code_files/my_main_code")]
)
await client.startup()
```
Sorry the PythonClient isn't that well documented. We wrote it mostly to aid in internal testing but it seems like there's a lot of interest.

I'll close this issue but feel free to reply/re-open if you run into any issues.
