### ISSUE TITLE
"ModuleNotFoundError: No module named 'mentat.terminal'" when installing from github

### ISSUE THREAD

**Issue by jochenstu** [AbanteAI/mentat#260]
Running metat after `python -m pip install git+https://github.com/AbanteAI/mentat.git` leads to

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/mentat", line 5, in <module>
    from mentat.terminal.client import run_cli
ModuleNotFoundError: No module named 'mentat.terminal'
```

The pip package is working fine (but I can't make it work with the 128k context window, which, I suspect, is not in that version yet)

System Version: macOS 14.1 (23B74), Python 3.11.5

**Comment by jakethekoenig** [comment]
Thanks for reporting. I see the same issue. I'll look into it. In the mean time you can also install with:
```
git clone https://github.com/AbanteAI/mentat.git
cd mentat

# install with pip in editable mode:
pip install -e .
```

**Comment by jochenstu** [comment]
Cheers, that got me on the right way!
