### ISSUE TITLE
Feature request: Tab completion for `/include` and `/exclude` arguments

### ISSUE THREAD

**Issue by jakethekoenig** [AbanteAI/mentat#299]

**Comment by biobootloader** [comment]
And /run, though that might be more complicated. Would be nice if we could easily take advantage of terminal bash completion scripts

**Comment by PCSwingle** [comment]
Going to start working on this, but it's a pretty difficult change (need to completely change how we do completions, and make it so that the client sends a request to the server to get all autocompletions, so they work for vscode and other clients as well)

**Comment by jakethekoenig** [comment]
Closed by: https://github.com/AbanteAI/mentat/pull/385
