### ISSUE TITLE
Mentat is using code from Aider, which has an Apache 2.0 license

### ISSUE THREAD

**Issue by paul-gauthier** [AbanteAI/mentat#302]
I'm just following up on the discussion we had recently on HackerNews.

https://news.ycombinator.com/item?id=38204886

https://github.com/search?q=repo%3AAbanteAI%2Fmentat+aider&type=pullrequests

It looks like you removed some of the Aider code from Mentat, but you never replied to my message about Aider's RepoMap code that was added to Mentat (renamed to CodeMap). This was added in your PR #66, and aider code and derivatives still seem to be present in your repo.

Has other Aider code been added to Mentat?

What is your plan for dealing with the remaining Aider code which has been incorporated into Mentat? I'm just checking because Aider's code is published under an Apache 2.0 license. So of course you are free to use it, but Apache 2.0 carries obligations for attribution and labeling of modified/derivative works.

**Comment by biobootloader** [comment]
Hey Paul, thanks for the message.

> It looks like you removed some of the Aider code from Mentat

We removed the Aider response format, but to be clear this was never Mentat's response format. It was implemented as part of a comparison of different response formats, and we didn't find significant differences in performance. For reference here's the PR removing the response format: https://github.com/AbanteAI/mentat/pull/259/files

> Aider's RepoMap code that was added to Mentat (renamed to CodeMap). This was added in your PR https://github.com/AbanteAI/mentat/pull/66, and aider code and derivatives still seem to be present in your repo.

Our CodeMap implementation is distinct and I wouldn't call it simply a rename of RepoMap. However there are similar sections of code, so I have added attribution to the file here: https://github.com/AbanteAI/mentat/pull/310

> Has other Aider code been added to Mentat?

No, we have discussed and I'm confident there's nothing else.
