### ISSUE TITLE
Add voice to text with whisper

### ISSUE THREAD

**Issue by gssakash-SxT** [AbanteAI/mentat#308]
Does Mentat have support for the vision API and the Whisper API from OpenAI?
[Vision API](https://platform.openai.com/docs/guides/vision)
[Whisper API](https://platform.openai.com/docs/guides/speech-to-text)

**Comment by jakethekoenig** [comment]
There's a PR to add vision https://github.com/AbanteAI/mentat/pull/289 I'm hopeful it will merge later this week. I don't think anyone is working on adding whisper. Would you use it?

**Comment by gssakash-SxT** [comment]
What you said seems to be ideal to me. Maybe other commentators can give us better UX ideas. But this works fine to me. I wonder what's the ideal way to integrate this into the Python Client

**Comment by jakethekoenig** [comment]
You want it for the python client? I was just thinking of adding it to the terminal. In my mind the purpose of the python client is mostly automation so it wouldn't make sense to add whisper

**Comment by gssakash-SxT** [comment]
Oh I see my feeling is that for most of the operations which Mentat performs, it'd be great to have an SDK as well (Which looks like the Python client) so that users can use it within code to use the functionality it provides for stuff they'd like
