### ISSUE TITLE
Removal of Git Root

### ISSUE THREAD

**Issue by gssakash-SxT** [AbanteAI/mentat#318]
I recently noticed that a new set of PRs have been started or are going to be started to eventually replace ``git_root`` with ``cwd`` to be able to use Sessions anywhere possible across Mentat. 

Can I know by when this can be implemented?

This is the [PR](https://github.com/AbanteAI/mentat/pull/272) I am talking about.

**Comment by jakethekoenig** [comment]
@waydegg

**Comment by biobootloader** [comment]
@gssakash-SxT these should be all merging in the next day or so!

**Comment by waydegg** [comment]
Hey @gssakash-SxT! We just merged the last PR for removing the dependency on git root. In the next release you'll be able to run Mentat anywhere (though if you install from the main branch you can do this right now!)
