### ISSUE TITLE
Get KeyError given by embedder when a large file is included

### ISSUE THREAD

**Issue by jakethekoenig** [AbanteAI/mentat#334]
When a large file is added to context the embedder gives a key error. I'm not exactly sure why since every file should be added to a batch as far as I can tell and OpenAI doesn't give us any errors.
![image](https://github.com/AbanteAI/mentat/assets/385534/98163999-8bd7-4ff8-a546-0e0c09df114f)

**Comment by granawkins** [comment]
It was a mistake when I made it originally - on line 136 we skip it, but then we didn't check if it was missing and set to 0. Easy fix in #291.
