### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by utpal4job** [AbanteAI/mentat#382]
Hello, i have checked your installation video and made the installation in the same way but when running "mentat ." on ssh then it's listing all the files on ssh. i am not getting like you are getting when running "mentat ."

one error is appearing after listing all the files. please check the  attached screenshot.
[
![Screenshot 2023-12-12 155639](https://github.com/AbanteAI/mentat/assets/3049092/216f7e65-4885-45ef-9cf3-5eec30a91316)
](url)

Regards.

**Comment by PCSwingle** [comment]
Hey @utpal4job! Thanks for catching this; we changed how we handled file includes recently and this was a bug that slipped through. I made PR #383 which should fix the bug; once it's merged, if you git clone mentat and try it out, it should be fixed. Thanks!

**Comment by biobootloader** [comment]
Mentat 1.0.6 is now available on pypi, so if you install with `pip install --upgrade mentat` you'll get the fixed version!

**Comment by utpal4job** [comment]
ok, thanks. i will check it.

**Comment by utpal4job** [comment]
Hello, thanks it's working fine but gpt4 model error appears. how can i change the gpt model? 

pls check the attached screenshot.
![error](https://github.com/AbanteAI/mentat/assets/3049092/ad387c97-f036-4af1-86f8-ce759d1027e9)

Regards.

**Comment by biobootloader** [comment]
There are ways to change the model, but there aren't models than can handle as many tokens as you are trying to include. I assume you are running with `mentat .` which adds everything in the directory to context. Instead how about you try running with `mentat path/to/file_a path/to/file_b`, adding just a couple files you want to work with?

A more advanced feature is to have it select files automatically based on what you ask. This is called auto context, and you can run with `mentat -a`

**Comment by utpal4job** [comment]
Hello, thanks for your reply. i have changed the gpt model and it's working fine.

Regards.

**Comment by biobootloader** [comment]
What model did you change it to?

**Comment by utpal4job** [comment]
I have used "gpt-4" instead of "gpt-4-1106-preview".
