### ISSUE TITLE
Feature Request: Separate Repo for Codium (or VS Code) Extension

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [AbanteAI/mentat#428]
Hello and thanks for this beautiful repo,

Do you have a separate repo / code base for the IDE extension on your current roadmap? If so, I'd be glad to test it with Ollama and write some comments too.

Best,
Orkut

**Comment by jakethekoenig** [comment]
Sorry for not responding sooner. The VSCode extension is [launched](https://github.com/AbanteAI/mentat/issues/552) and the code is in this repo under mentat-vscode.

**Comment by orkutmuratyilmaz** [comment]
Thank you @jakethekoenig :+1:
