### ISSUE TITLE
Question : Is Mentat using ChromaDB like a LSTM or is it just used for embeddings?

### ISSUE THREAD

**Issue by gssakash-SxT** [AbanteAI/mentat#485]
Hi, I recently noticed that Mentat now uses ChromaDB.
Are you guys using ChromaDB for any sort of RAG processing during the process of code generation through Mentat?
OR is ChromaDB just being used for the calculation of Embeddings and nothing else?

**Comment by biobootloader** [comment]
It's used by the auto-context system (to use, run with `-a` flag, aka `mentat -a`). ChromaDB stores the embeddings and searches them for the RAG yes
