### ISSUE TITLE
Error when deployment_name is different from model name in Azure

### ISSUE THREAD

**Issue by zhh210** [AbanteAI/mentat#489]
Microsoft is a genius in making simple things overcomplicated and confusing. This happened again that the deployment name and model name can be different in Azure OpenAI. Is it possible to allow adding an additional key `deployment_name` to `~/.mentat/.mentat_config.json`?  For example, my model name is `gpt-3.5-turbo` but my `depoyment_name` is `gpt-35-turbo`. This will be troublesome because currently mentat only allow using one variable `model`. If I set `model="gpt-3.5-turbo"`, the azure chat.completions.create() [call](https://github.com/AbanteAI/mentat/blob/main/mentat/llm_api_handler.py#L386) will fail because there is no deployment of `"gpt-3.5-turbo"`. However if I set `model="gpt-35-turbo"`, the _validate_key() [call ](https://github.com/AbanteAI/mentat/blob/main/mentat/llm_api_handler.py#L204)will get an error saying `"gpt-35-turbo"` doesn't exist in known model key.

Note: the culprit is really Azure's stupid way of defining the argument `model` in `client.chat.completions.create` is using deployment_name rather than model_name. See Azure's OpenAI 1.x [example](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/migration?tabs=python-new%2Cdalle-fix).

**Comment by gssakash-SxT** [comment]
++ facing the same issue. Mentat isn't exactly working right now and it doesn't look like my Azure Deployment is down as I am using the same Azure OpenAI on other applications I have and all of them work smoothly

**Comment by zhh210** [comment]
> ++ facing the same issue. Mentat isn't exactly working right now alongside Azure and I get a 404 and it doesn't look like my Azure Deployment is down as I am using the same Azure OpenAI on other applications I have and all of them work smoothly

It worked after I modified this [line](https://github.com/AbanteAI/mentat/blob/main/mentat/llm_api_handler.py#L386) to map `model` to `deployment_name` in the source code on my local installation. But this is kind of a hacky quick-fix. Adding an option in config to skip _validate_key() might a better alternative.

**Comment by biobootloader** [comment]
Thanks for flagging this!

It seems like a good approach would be to add an optional `azure_deployment_name` to config and use that for the actual calls, while still using the model name for checking if the model is valid and what it costs / token limits are. 

If it's set the user would just have to ensure the model name is accurate for that deployment so cost estimates are correct.

**Comment by biobootloader** [comment]
@zhh210 @gssakash-SxT , this should now be fixed in the latest release! Let me know if you still have any issues.

**Comment by zhh210** [comment]
Thanks @biobootloader ! confirming that the latest fix works! Now Azure OpenAI will work when  putting {"model": <azure_deployment_name>} to ~/.mentat/.mentat_config.json.
