### ISSUE TITLE
Git Diff problem caused by Sampler when using a Virtual environment

### ISSUE THREAD

**Issue by gssakash-SxT** [AbanteAI/mentat#491]
I mainly interact with Mentat through the ``python_client`` and while doing this I noticed that the ``GIT DIFF`` process required by the library is being done either by the Sampler or the Revisor which has problems.

The Problem : I noticed that when I call the functions inside of the python client, all of the packages inside of a virtual environment I create on my local get added as well which are unnecessary.

This sometimes causes the Sampler and Revisor to fail and I get a Git Diff related error from the GitPython library. 

However, when the code runs, Mentat adds on these extra virtual environment files to its execution process and that slows it down quite a bit. A temporary fix I found was to gitignore virtual environment files.

**Comment by jakethekoenig** [comment]
Thanks for reporting this. We made an internal tool, the sampler, to make a mentat conversation into a sample, something that can be easily specialized into a benchmark test or finetuning example. In order to make it work we record some state about the git repo at startup but it wasn't done in a very safe way. I put it behind a flag in the config so it won't run automatically.

**Comment by jakethekoenig** [comment]
Also @gssakash-SxT I'd be interested in talking about how you use the `python_client` sometime if you're open to it. We originally made it for testing but we're thinking about exposing it as the default export so you can import it as `from mentat import mentat` and changing the interface. Renaming `call_mentat_auto_accept` to just `call` maybe. Probably leaving the existing functions so as not to be a breaking change. Do you have any thoughts?

**Comment by biobootloader** [comment]
@gssakash-SxT @jakethekoenig's fix is in the latest release!
