### ISSUE TITLE
your OpenAI API key doesn't have access to gpt-4-0314

### ISSUE THREAD

**Issue by choskeli** [AbanteAI/mentat#53]
I get the error `your OpenAI API key doesn't have access to gpt-4-0314` when I try to run mentat. I thought GPT-4 API was generally available now? Do I need to change the code to use a specific version of GPT-4 API?

**Comment by D-Raza** [comment]
The GPT-4 models are only available if you've made [a payment of $1 or more for API usage](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4)

To see which models are available for you, see [list models](https://platform.openai.com/docs/api-reference/models/list?lang=python)

If you don't have access to GPT-4, you can check out `mentat/llm_api.py` and make some edits to use 3.5 instead. Keep in mind 3.5 isn't very good at mentat.

**Comment by inventor2525** [comment]
This seems to be false, I waited until a $8 charge was made (which was only made 30 days after starting, not on first of the month [note for anyone else]) and I still do not have access to 32k.

Upon contacting OpenAI, I got this:




Hello,
Thank you for reaching out to OpenAI support.
We understand that you're interested in GPT-4 32k API.
Priority access to the GPT-4 32k API is currently available for customers on an enterprise agreement with OpenAI.
Rest assured that we're in the process of granting access to the 8K and 32K engines at different rates, depending on capacity. As a result, you may receive access to them at separate times. We don't have a specific timeframe for when you'll be granted access, and we appreciate your patience during this ramp-up!
If you're a ChatGPT Plus subscriber, you can access GPT-4 through chat.openai.com and our iOS/Android apps with an hourly usage cap. We'll adjust this limit based on demand and how well the system is performing. Please note that ChatGPT Plus subscription doesn't include API access.
Please let us know if there’s anything else we can help you with.

**Comment by inventor2525** [comment]
I do however have access to 8k GPT4 from the beginning, but maybe that's because I was on the trial for GPT3.5 way back, but I never actually got charged anything as I had $20 credit in the trial.

**Comment by biobootloader** [comment]
@inventor2525 you don't need GPT-4-32k to use Mentat, you just need GPT-4-0314 (it's regular 8k context GPT-4, but the version that was released in March)
