### ISSUE TITLE
"Provider is required when unknown models are used" but no way to set provider for gpt-4-turbo.

### ISSUE THREAD

**Issue by CarlQLange** [AbanteAI/mentat#560]
Annoyingly because of Textual I can't even see the full traceback - I can't find where the error text is even generated in Mentat or in Spice.

My mentat_config.json:

```
{
        "model": "gpt-4-turbo-preview",
        "maximum_context": 128000,
        "auto_context_tokens": 8000
}
```

Bit frustrating. Is there some way I should set this that I'm not seeing?

**Comment by CarlQLange** [comment]
I got around this by monkeypatching https://github.com/AbanteAI/spice/blob/main/spice/models.py and adding a line for gpt-4-turbo

```
GPT_4_TURBO_PREVIEW = TextModel("gpt-4-turbo-preview", OPEN_AI, 128000)
```

**Comment by biobootloader** [comment]
Sorry about that! I've added `gpt-4-turbo-preview` and all the new OpenAI models from today to Spice and released a new version. Mentat isn't updated to use the new spice version yet though, I'm not sure if there are conflicts - @PCSwingle can you upgrade Mentat's spice dependency tomorrow?

**Comment by PCSwingle** [comment]
Hey @CarlQLange! Just pushed a PR that fixes this and lets you set the provider via config. Thanks for catching this!

**Comment by CarlQLange** [comment]
Thanks a bunch!
