### ISSUE TITLE
improve trajectory reports

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#584]
several things to do:

- move the llm response stats up next to the ParsedModelEvent UUID
- "Show More" and "Show Less" should only appear if the text is long enough to get cut off. And maybe there's something cleaner than "show more" "show less" ? 
- make "Model Action" events stand out more in the timeline, as these are the main things of interest

**Comment by biobootloader** [comment]
@MentatBot

**Comment by jakethekoenig** [comment]
@mentatbot
