### ISSUE TITLE
Separate Core Logic from Terminal Interface

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#63]
To prepare for future editor extensions and other interfaces, we need to separate the core logic from the terminal interface (both input and output). The goal is to allow for multiple interfaces: terminal, VSCode extension, NeoVim extension, etc

**Comment by biobootloader** [comment]
A few other considerations:

The `UserInputManager` class as written would only be used for the terminal interface, since it's setup for `prompt_toolkit` completions, etc. It also has an `ask_yes_no` method that re-asks the user until it gets a yes or no: https://github.com/biobootloader/mentat/blob/3a77290355f8797971f83bbeaa172a41d8189bfe/mentat/user_input_manager.py#L84-L92

The implementation will have to watch out for how it handles these errors as well, maybe changing some of them even: https://github.com/biobootloader/mentat/blob/3a77290355f8797971f83bbeaa172a41d8189bfe/mentat/app.py#L72-L76

**Comment by biobootloader** [comment]
The "MentatRunner" will also need a way to report that core mentat has crashed, and why, to the interface

**Comment by biobootloader** [comment]
@granawkins @waydegg what are your thoughts on this?

**Comment by waydegg** [comment]
I like the direction you're going with this.

At a glace I think we'll need base classes/abstractions for:
- The LLM loop (e.g. `MentatRunner`)
- User input (handling shortcuts like ctrl-c and mouse input for IDE extensions)
- Mentat output (handle output for non-terminal interfaces)

Having these 3 abstractions would allow people to start building working plugins/extensions without breaking the core logic.

**Comment by waydegg** [comment]
Added in #119
