### ISSUE TITLE
Add mypy to github action lint checks

### ISSUE THREAD

**Issue by waydegg** [AbanteAI/mentat#75]
I'm assuming we're using mypy since we have `mypy-extensions` as a dependency in the `requirements.txt`, however we don't have any checks setup in GH actions. Would be pretty trivial to add a command that checks for this.

@biobootloader any specific reason why choosing mypy over Pyright? I'm not sure what the best choice would be tbh.

**Comment by biobootloader** [comment]
I don't know the differences between mypy and Pyright, but it would be great to have checks added to GH actions (and I'm sure we've got issues to fix!)

Feel free to add whichever you think is best!

**Comment by PCSwingle** [comment]
We aren't using mypy (to my knowledge); it looks like it's a requirement of black (pip show mypy-extensions). It would definitely be good to use mypy I think (since it makes typing mandatory, right?) but that would be a pretty big change

**Comment by waydegg** [comment]
I think the default configuration for mypy is pretty flexible on how strict everything needs to be typed (there's a ton of config options and plugins you can setup to dial this in). The pyright default config doesn't raise too many linting errors with how the project is currently typed atm, so enforcing either pyright or mypy at this stage of the project wouldn't be that much work. 

I'll create a small PR that fixes the typing errors and adds linting checks. Will also put together a list of existing python projects that do a good job at enforcing this for reference. There's definitely a balance b/w no type enforcement at all and enforcing strict type defs for everything.

**Comment by biobootloader** [comment]
Sounds good! Initially what we want are checks that the types we have defined are accurate (or remain accurate as we make changes)

**Comment by waydegg** [comment]
Closing this since we've added Pyright to lint checks
