### ISSUE TITLE
Add a test of code map fallback behavior

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#77]
Once code maps are merged (https://github.com/biobootloader/mentat/pull/66), write a test (not a benchmark, it should run on GH actions) that checks that calling `CodeMap.get_message` with different `token_limits` correctly transitions between a full map (with signatures), a map without signatures, and just a file map.

Reason for test: this is an important feature that seems like it be easy for us to not immediately notice if we broke it on accident

**Comment by granawkins** [comment]
This was added in #115 by [this test](https://github.com/AbanteAI/mentat/blob/0d0e82c290c4f1fa53ac2f69dd63945e01009709/tests/code_context_test.py#L268).
