### ISSUE TITLE
Real World Performance Benchmark

### ISSUE THREAD

**Issue by jakethekoenig** [AbanteAI/mentat#97]
In order to get a realistic sense of Mentat's performance it'd be best to compare the code it generates to human generated code. We could pick out some high quality open source github repos with good standards around writing commit messages, issues and pull requests. Checkout the code before a commit and prompt mentat with produce a diff that accomplishes $COMMIT_MESSAGE towards solving $ISSUE. We can then evaluate it in two ways:
1. Does it modify the same files as the original commit?
2. We can feed both diffs to gpt and ask which is higher quality.

I'm interested in evaluating 1 even though it's not that informative on its own because it will give us a benchmark to evaluate as we implement ideas aimed at expanding the model's effective context, [Issue 3](https://github.com/biobootloader/mentat/issues/3).

We can discuss other ideas for benchmarks here and break good ideas out into separate issues.

**Comment by biobootloader** [comment]
One difficulty with doing this now is it'll have to be small projects that can fit all fit in context. Although we could just give it the files that are modified (which would precluded your first evaluation on which files it modifies).

Informative enough commit messages might be too hard to find, but yeah issues / PR descriptions might work!
