### ISSUE TITLE
Use embeddings of files/functions to select context for prompt

### ISSUE THREAD

**Issue by granawkins** [AbanteAI/mentat#99]
We'd like mentat to select files related to a prompt based on how similar their embeddings are. I've setup a test in a Jupyter Notebook (I can share directly). The process is:

1. Get embeddings from openai using `text-embedding-ada-002`. We can send up to 8192 tokens per API call, either a string or a list of strings (batch).
2. I use `ast` and `astor` to parse Python functions from the mentat code. There doesn't seem to be a one-stop solution to parsing different languages, but we have some leads.
3. I use cosine similarity on the embeddings of prompt vs each file/function, them sort them and return the top N.

I wrote 3 test prompts, with a list of files and functions I expected to see. Then I ran the algo and returned the top 10, and counted how many of the expected were included.

### Results
Prompt: Give me a summary of how asyncio is used in the code.
Files: 3/5
Functions: 1/4

Prompt: Add a new pytest fixture function in conftest to call git commands and return the results. Then, replace calls to subprocess/git in the tests with that new fixture.
Files: 3/4
Functions: 3/10

Prompt: Allow the user to use gpt-3.5 instead of gpt-4, but give them a warning. Add relevant, cost, metadata, etc for the new model, as well as tests and stats.
Files: 2/3
Functions: 2/7

**Comment by biobootloader** [comment]
> There doesn't seem to be a one-stop solution to parsing different languages, but we have some leads.

One promising direction would be ctags, since we already use them to parse the codebase for Code Maps: https://github.com/biobootloader/mentat/blob/cb063a083a0da7e7f55bb3ca5f0599455b97a099/mentat/code_map.py

We could embed each element at all levels (files, classes, functions, etc). These levels may not always mean the same thing in different languages, but maybe that doesn't matter!

**Comment by ryanfreckleton** [comment]
For what it's worth, tree-sitter seems to be The Right Way (TM) to do this sort of thing.

https://tree-sitter.github.io/tree-sitter/

**Comment by granawkins** [comment]
Embeddings are added in #144 - they're off by default and have limited accuracy so far. Some follow-on tasks:

- [ ] More benchmark tests
- [ ] Add a `/search <prompt>` command, using `embeddings.get_feature_similarity_scores`
- [ ] Optimize the database and vector comparison. Currently we're using gzip and cosine-similarity. Maybe a vector database could replace both of these?
- [ ] Add a loading message and a cost summary when fetching embeddings

**Comment by gssakash-SxT** [comment]
Is this implemented in #460 ? 
Or has this feature been deprecated instead?

**Comment by jakethekoenig** [comment]
It's actually been implemented for a while. This last PR migrated the embeddings database from our own sqlite db to a chromadb. By default we only use the files explicitly added but if you start mentat with `mentat -a` "a" for autocontext then we use embeddings to choose files. You can control how many tokens are added by adding a number. 5000 by default. Docs [here](https://docs.mentat.ai/en/latest/user/context.html).
